package com.mexazon.app.model;

import jakarta.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/**
 * Entity class that maps to the database table 'postal_code_catalog'.
 * Each object of this class represents one record in the table.
 */
@Entity
@Table(name = "postal_code_catalog")
public class PostalCodeCatalog implements Serializable {

    /**
     * Primary key for the table.
     * This field is automatically generated by the database (auto-increment).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Postal code field (for example: 64000, 64100, etc.).
     * The column name in the database is 'codigo_postal'.
     * It cannot be null.
     */
    @Column(name = "codigo_postal", nullable = false)
    private String codigoPostal;

    /**
     * Neighborhood or colony name.
     * The column name in the database is 'colonia'.
     * It cannot be null.
     */
    @Column(name = "colonia", nullable = false)
    private String colonia;

    /**
     * Municipality or district name.
     * Optional, but helps to group postal codes by region.
     */
    @Column(name = "alcaldia", length = 100, nullable = true)
    private String alcaldia;

    // ---------- Constructors ----------

    public PostalCodeCatalog() {}

    public PostalCodeCatalog(String codigoPostal, String colonia, String alcaldia) {
        this.codigoPostal = codigoPostal;
        this.colonia = colonia;
        this.alcaldia = alcaldia;
    }

    // ---------- Getters and Setters ----------

    public Long getId() {
        return id;
    }

    public String getCodigoPostal() {
        return codigoPostal;
    }

    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    public String getColonia() {
        return colonia;
    }

    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    public String getAlcaldia() {
        return alcaldia;
    }

    public void setAlcaldia(String alcaldia) {
        this.alcaldia = alcaldia;
    }

    // ---------- equals() and hashCode() ----------
    // These methods are required for comparing entities properly.
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof PostalCodeCatalog)) return false;
        PostalCodeCatalog that = (PostalCodeCatalog) o;
        return Objects.equals(id, that.id);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}


